version: "3.8"

services:

  composer:
    image: composer:latest
    volumes:
      - ./code:/app
    working_dir: /app 

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./code:/app
    #specify the working directory of artisan command  
    entrypoint: ["php", "/app/artisan"]