version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8099:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./code:/app
    depends_on:
      - php-runtime

  php-runtime:
    build:
      context: php
      dockerfile: php.Dockerfile
    env_file:
      - ./php/php_app.env    
    volumes:
      - ./code:/app

  composer:
    image: composer:latest
    volumes:
      - ./code:/app
    working_dir: /app 

