version: "3.8"

volumes:
  db_data:

services:

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8099:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./code:/app
    depends_on:
      - php-runtime

  php-runtime:
    build:
      context: php
      dockerfile: php.Dockerfile
    container_name: php-runtime
    ports:
      - "9000:9000"
    env_file:
      - ./env-files/php_app.env    
    volumes:
      - ./code:/app
    depends_on:
      - db    

  composer:
    image: composer:latest
    volumes:
      - ./code:/app
    working_dir: /app 

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db:3306
    depends_on:
      - db  

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./env-files/php_app.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
